# Change these first
owner: appqualia # Your GitHub organization or username, where this repository lives
repo: cd-status # The name of this repository

sites:
  - name: ComicDesigner LP
    url: https://comicdesigner-alpha.vercel.app/lp/ja
  
  
status-website:
  # themeUrl: https://comicdesigner-alpha.vercel.app/status-theme.css
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  name: ComicDesigner Status
  baseUrl: /cd-status
  themeUrl: https://comicdesigner-alpha.vercel.app/status-theme.css
  navbar:
    - title: Home
      href: https://comicdesigner-alpha.vercel.app/lp/ja
    - title: Status
      href: /cd-status/
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  # name: Upptime
  introTitle: "ComicDesigner Status Page"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  # navbar:
  #   - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
  customBodyHtml: |
    <div class="lp-topbar">
      <a class="lp-brand" href="https://comicdesigner-alpha.vercel.app/lp/ja">ComicDesigner</a>
      <span class="lp-sep">/</span>
      <span>Status</span>
    </div>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
